Id: Mojang.Minecraft
Version: 2.1.14401
Name: Minecraft Launcher
Publisher: Mojang
License: Copyright (c) Mojang
LicenseUrl: https://account.mojang.com/documents/minecraft_eula
AppMoniker: minecraft
Description: Official launcher for Minecraft, a sandbox voxel game.
Homepage: https://www.minecraft.net
Installers:
  - Arch: x86
    Url: https://launcher.mojang.com/download/MinecraftInstaller.msi
    Sha256: DAB483B7BB789802E81865953809FA7EFAA929FEB292317221B74E0F4373166D
    InstallerType: msi
