Id: Tencent.WeChat
Name: Tencent WeChat
Version: 2.9.0.1000
Publisher: Tencent Technology (Shenzhen) Company Limited
Author: Tencent Technology (Shenzhen) Company Limited
Homepage: https://www.wechat.com
Description: Connecting a billion people with calls, chats and more.
License: Copyright (C) Tencent Corporation
LicenseUrl: https://www.wechat.com/en/service_terms.html
Tags: WeChat, WeiXin, IM
MinOSVersion: 10.0.0.0
InstallerType: exe
Installers:
  - Arch: x86
    Url: https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
    Sha256: 973b429c4f9c1882340c3b8bfa066ae159b5dd409f876538e3820efbeb0a5ab4
    Switches:
      Silent: /S
      SilentWithProgress: /S
