Id: CPUID.CPU-Z
Publisher: CPUID
Name: CPU-Z
Version: 1.92.0.0
License: Copyright (C) CPUID
InstallerType: EXE
AppMoniker: 
Description: CPU-Z is a freeware that gathers information on some of the main devices of your system
Homepage: https://www.cpuid.com/softwares/cpu-z.html
Installers:
  - Arch: x64
    Url: http://download.cpuid.com/cpu-z/cpu-z_1.92-en.exe
    Sha256: 947C234B7A9F74449081AF0124F8288DD9F87D54281DE4FD55185414BC8EE046
    Switches:
      Silent: /VERYSILENT
      SilentWithProgress: /VERYSILENT
