Id: alcpu.coretemp
Publisher: alcpu
Name: CoreTemp
Version: 1.15.1.0
License: Freeware
InstallerType: EXE
LicenseUrl: https://www.alcpu.com/CoreTemp/commercial.html
Description: Core Temp is a compact, no fuss, small footprint, yet powerful program to monitor processor temperature and other vital information.
Homepage: https://www.alcpu.com/CoreTemp/
Installers:
  - Arch: x64
    Url: https://www.alcpu.com/CoreTemp/Core-Temp-setup.exe
    Sha256: EB4BF340404631DFBE1653B9D7B207421E9C7EFD9BD1B87CFD6CB861744975D2
    Switches:
      Silent: /VERYSILENT
      SilentWithProgress: /VERYSILENT
