Id: Microsoft.VisualStudioCode
Version: 1.45.1                                           
Name: Visual Studio Code                                          
Publisher: Microsoft Corporation                                       
Homepage: https://visualstudio.microsoft.com/downloads/
License: Copyright (c) Microsoft Corporation
Description: Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications. Visual Studio Code is free and available on your favorite platform - Linux, macOS, and Windows.
AppMoniker: vscode
Commands: code
Installers: 
    - Arch: x64
      Url: https://update.code.visualstudio.com/1.45.1/win32-x64-user/stable
      InstallerType: Inno
      Sha256: 8858955289bd86743b356df90a8d45e608000973e66be17cfbe9b70adbd77209
