Id: DMM.GamePlayer
Version: 2.5.4
Name: DMM Game Player
Publisher: DMM
License: Copyright (c) since 1998 DMM
AppMoniker: dmmgameplayer
Tags: dmm, gameplayer
Homepage: https://games.dmm.com/
Installers:
  - Arch: x86
    Url: http://dl-gameplayer.dmm.com/admin/win/installer/DMMGamePlayerSetup.exe
    Sha256: 869B66E885FD6C79976F176EE679B85CE894086BBD2675923FD8F5C66F523C69
    InstallerType: inno
