Id: LutzRoeder.Netron
Version: 4.1.8
Name: Netron
Publisher: Lutz Roeder
AppMoniker: netron
Description: Visualizer for neural network, deep learning and machine learning models
License: Copyright (c) Lutz Roeder
Homepage: https://github.com/lutzroeder/netron
Installers:
  - Arch: x86
    InstallerType: nullsoft
    Url: https://github.com/lutzroeder/netron/releases/download/v4.1.8/Netron-Setup-4.1.8.exe
    Sha256: 86D4ACD5E6E2802C129FA287C96F370F59546E359B3CB7650A9B9C30DE010F06
