Id: VoyagerX.Vrew
Publisher: VoyagerX
Name: Vrew
Version: 0.4.18
License: VoyagerX, Inc. © 2018 All Rights Reserved.
Homepage: https://vrew.voyagerx.com/
InstallerType: exe
Installers:
  - Arch: x64
    Url: https://vrew-files.voyagerx.com/Vrew-0.4.18.exe
    Sha256: E0DBBFA4B427A89B1376A5C09A87B6C2DE896514C5B517DE0025871248BE40ED
